export default {

    // Auth
    HOME: 'HOME',
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    VERIFY_EMAIL: 'VERIFY_EMAIL',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    CREATE_BLOCK: 'CREATE_BLOCK',
    CREATE: 'CREATE',
    BLOCK_PAGE: 'BLOCK_PAGE',
    SEARCH: 'SEARCH',
}