name: Linter

on:
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: Lint codebase
    runs-on: ubuntu-latest

    steps:
      - name: Auto-cancel redundant job
        uses: technote-space/auto-cancel-redundant-job@v1
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up node environment
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn
      - name: Format
        run: yarn format
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: echo "Changes exist"
