name: Expo Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up node environment
        uses: actions/setup-node@v2
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - run: yarn install
      - run: expo publish